Mistral-7B-Base-SFT-SimPER:
  prompt_template: templates/mistral_base.txt
  fn_completions: vllm_local_completions
  completions_kwargs:
    model_name: outputs/Mistral-7B-Base-SFT-SimPER
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
    batch_size: 900
  pretty_name: Mistral-7B-Base-SFT-SimPER
